### ISSUE TITLE
Compile time example?

### ISSUE THREAD

**Issue by baryluk** [skoppe/perfect-hash#2]
It is unclear from readme if generator can be used during compile time.

Would be nice to have a function, like this:

```dlang
mixin(generate_mixin(code(generatete(keys), "MyTable");
MyTable my_table;
```

that creates a class/struct, and operator overloads to make it happen.

```dlang
mixin generate_table_type!keys MyTable;
```

is another option.

**Comment by skoppe** [comment]
Theoretically there is a perfect hash function for each set of keys such that the length of the hash's state (N) is equal to the number of keys (K). Finding one is rather tricky.

The algorithm I used to create the hash function does a random search to minimize N. It starts at 2*K and goes down towards K according to `N = N - (max(1, (N - K) / 20));`, with a time limit of 1_000_000 hnsec by default.

There is thus a tradeoff between search time and hash state's size. A shorter state means faster hashing but it takes longer to find.

There are a few problems with doing this at compile time:

1) the clock isn't available at CTFE
2) most people who want a perfect-hash function want a low N, thus it would have a big impact on compile times

The solution I implemented was to provide a `toDModule` function that spits out a D file containing the hash function. You can use that in you build.
